### ISSUE TITLE
Crucible recipes not functioning properly

### ISSUE THREAD

**Issue by chronicChthonic** [mosharky/Mos-Mods#23]
Certain crucible recipes don't seem to be functioning properly. I haven't tested every recipe, but it seems to be recipes where there are multiple of one ingredient and stirring on the same step. The last item, instead of making the product, just changes the water color again. This makes the Eidolon mod impossible to progress through.

**Comment by mosharky** [comment]
I've barely touched Eidolon recipes in this modpack, so this I would assume this is a problem with the Eidolon mod. That being said, I'm not working on this modpack anymore unfortunately. I've moved onto 1.18 with a much more ambitious version of this modpack (not currently released).

You could try manually updating the [Eidolon Data Recipes](https://www.curseforge.com/minecraft/mc-mods/eidolon-data-recipes) mod that this modpack uses. Not sure if this is a problem with that mod, though.

**Comment by chronicChthonic** [comment]
I went into the eidolon recipes .json files and removed the line for stirring from all the recipes that fit my description above. For some reason you still need to stir, but it seems to work now.

Also I'm happy to hear that you're working on a modpack for 1.18! I'm really enjoying this modpack, so I'll be looking forward to the new one.
